services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/geo-partner-finder
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
        networks:
            - app-network

    postgres:
        image: postgres:16-alpine
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=geo-partner-finder
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        networks:
            - app-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d btg-order-reporting" ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
networks:
    app-network:
        driver: bridge